export const initialFromData = [
  {
    id: 802,
    code: "DAC",
    name: "Hazrat Shahjalal Intl Airport",
    cityCode: "DAC",
    cityName: "Dhaka",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Dhaka",
  },
  {
    id: 1633,
    code: "JED",
    name: "King Abdulaziz International Airport",
    cityCode: "JED",
    cityName: "Jeddah",
    countryName: "SAUDI ARABIA",
    countryCode: "SA",
    address: "Jeddah",
  },
  {
    id: 2162,
    code: "MED",
    name: "Prince Mohammad Bin Abdulaziz Intl Airport",
    cityCode: "MED",
    cityName: "Madinah",
    countryName: "SAUDI ARABIA",
    countryCode: "SA",
    address: "Madinah",
  },
  {
    id: 932,
    code: "DXB",
    name: "Dubai Intl Airport",
    cityCode: "DXB",
    cityName: "Dubai",
    countryName: "UNITED ARAB EMIRATES",
    countryCode: "AE",
    address: "Dubai",
  },
  {
    id: 5,
    code: "JFK",
    name: "John F Kennedy Intl ",
    cityCode: "NYC",
    cityName: "New York",
    countryName: "UNITED STATES",
    countryCode: "US",
    address: "New York",
  },
  {
    id: 802,
    code: "DAC",
    name: "Hazrat Shahjalal Intl Airport",
    cityCode: "DAC",
    cityName: "Dhaka",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Dhaka",
  },
];

export const initialToData = [
  {
    id: 1633,
    code: "JED",
    name: "King Abdulaziz International Airport",
    cityCode: "JED",
    cityName: "Jeddah",
    countryName: "SAUDI ARABIA",
    countryCode: "SA",
    address: "Jeddah",
  },
  {
    id: 2162,
    code: "MED",
    name: "Prince Mohammad Bin Abdulaziz Intl Airport",
    cityCode: "MED",
    cityName: "Madinah",
    countryName: "SAUDI ARABIA",
    countryCode: "SA",
    address: "Madinah",
  },
  {
    id: 932,
    code: "DXB",
    name: "Dubai Intl Airport",
    cityCode: "DXB",
    cityName: "Dubai",
    countryName: "UNITED ARAB EMIRATES",
    countryCode: "AE",
    address: "Dubai",
  },
  {
    id: 5,
    code: "JFK",
    name: "John F Kennedy Intl ",
    cityCode: "NYC",
    cityName: "New York",
    countryName: "UNITED STATES",
    countryCode: "US",
    address: "New York",
  },
  {
    id: 802,
    code: "DAC",
    name: "Hazrat Shahjalal Intl Airport",
    cityCode: "DAC",
    cityName: "Dhaka",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Dhaka",
  },
];

export const suggestion = [
  {
    id: 802,
    code: "DAC",
    name: "Hazrat Shahjalal Intl Airport",
    cityCode: "DAC",
    cityName: "Dhaka",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Dhaka",
    continent: "domestic",
  },
  {
    id: 4402,
    code: "CXB",
    name: "COX's Bazar Airport",
    cityCode: "CXB",
    cityName: "Cox's Bazar",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Cox's Bazar",
    continent: "domestic",
  },
  {
    id: 4395,
    code: "ZYL",
    name: "Sylhet Osmany Intl Airport",
    cityCode: "ZYL",
    cityName: "Sylhet",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Sylhet",
    continent: "domestic",
  },
  {
    id: 4406,
    code: "SPD",
    name: "Saidpur Airport",
    cityCode: "SPD",
    cityName: "Saidpur",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Saidpur",
    continent: "domestic",
  },
  {
    id: 4405,
    code: "RJH",
    name: "Shah Makhdum Airport",
    cityCode: "RJH",
    cityName: "Rajshahi",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Rajshahi",
    continent: "domestic",
  },
  {
    id: 4403,
    code: "BZL",
    name: "Barishal Airport",
    cityCode: "BZL",
    cityName: "Barishal",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Barishal",
    continent: "domestic",
  },
  {
    id: 621,
    code: "CGP",
    name: "Shah Amanat Int Airport",
    cityCode: "CGP",
    cityName: "Chittagong",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Chittagong",
    continent: "domestic",
  },
  {
    id: 578,
    code: "CCU",
    name: "Netaji Subhas Chandra Bose Intl ",
    cityCode: "CCU",
    cityName: "Kolkata",
    countryName: "INDIA",
    countryCode: "IN",
    address: "Kolkata",
    continent: "asia",
  },
  {
    id: 2109,
    code: "MAA",
    name: "Chennai Intl Airport",
    cityCode: "MAA",
    cityName: "Chennai",
    countryName: "INDIA",
    countryCode: "IN",
    address: "Chennai",
    continent: "asia",
  },
  {
    id: 3232,
    code: "SIN",
    name: "Changi Intl Airport",
    cityCode: "SIN",
    cityName: "Singapore",
    countryName: "SINGAPORE",
    countryCode: "SG",
    address: "Singapore",
    continent: "asia",
  },
  {
    id: 369,
    code: "BKK",
    name: "Suvarnabhumi Intl Airport",
    cityCode: "BKK",
    cityName: "Bangkok",
    countryName: "THAILAND",
    countryCode: "TH",
    address: "Bangkok",
    continent: "asia",
  },
  {
    id: 1833,
    code: "KTM",
    name: "Tribuvan Intl Airport",
    cityCode: "KTM",
    cityName: "Kathmandu",
    countryName: "NEPAL",
    countryCode: "NP",
    address: "Kathmandu",
    continent: "asia",
  },
  {
    id: 547,
    code: "CAN",
    name: "Guangzhou Baiyun International Airport",
    cityCode: "CAN",
    cityName: "Guangzhou",
    countryName: "CHINA",
    countryCode: "CN",
    address: "Guangzhou",
    continent: "asia",
  },
  {
    id: 3214,
    code: "PVG",
    name: "Pudong Intl Airport",
    cityCode: "SHA",
    cityName: "Shanghai",
    countryName: "CHINA",
    countryCode: "CN",
    address: "Shanghai",
    continent: "asia",
  },
  {
    id: 3659,
    code: "NRT",
    name: "Narita International Airport",
    cityCode: "TYO",
    cityName: "Tokyo",
    countryName: "JAPAN",
    countryCode: "JP",
    address: "Tokyo",
    continent: "asia",
  },
  {
    id: 3178,
    code: "ICN",
    name: "Incheon Intl Airport",
    cityCode: "SEL",
    cityName: "Seoul",
    countryName: "KOREA, REPUBLIC OF",
    countryCode: "KR",
    address: "Seoul",
    continent: "asia",
  },
  {
    id: 2308,
    code: "SVO",
    name: "Sheremetyevo Intl Airport",
    cityCode: "MOW",
    cityName: "Moscow",
    countryName: "RUSSIA",
    countryCode: "RU",
    address: "Moscow",
    continent: "asia",
  },
  {
    id: 1740,
    code: "KHI",
    name: "Quaid E Azam Intl ",
    cityCode: "KHI",
    cityName: "Karachi",
    countryName: "PAKISTAN",
    countryCode: "PK",
    address: "Karachi",
    continent: "asia",
  },
  {
    id: 1566,
    code: "ISB",
    name: "Islamabad Intl ",
    cityCode: "ISB",
    cityName: "Islamabad",
    countryName: "PAKISTAN",
    countryCode: "PK",
    address: "Islamabad",
    continent: "asia",
  },
  {
    id: 679,
    code: "CMB",
    name: "Bandaranaike Intl Airport",
    cityCode: "CMB",
    cityName: "Colombo",
    countryName: "SRI LANKA",
    countryCode: "LK",
    address: "Colombo",
    continent: "asia",
  },
  {
    id: 2255,
    code: "MLE",
    name: "Male Intl Airport",
    cityCode: "MLE",
    cityName: "Male",
    countryName: "MALDIVES",
    countryCode: "MV",
    address: "Male",
    continent: "asia",
  },
  {
    id: 3178,
    code: "ICN",
    name: "Incheon Intl Airport",
    cityCode: "SEL",
    cityName: "Seoul",
    countryName: "KOREA, REPUBLIC OF",
    countryCode: "KR",
    address: "Seoul",
    continent: "asia",
  },
  {
    id: 2308,
    code: "SVO",
    name: "Sheremetyevo Intl Airport",
    cityCode: "MOW",
    cityName: "Moscow",
    countryName: "RUSSIA",
    countryCode: "RU",
    address: "Moscow",
    continent: "asia",
  },
  {
    id: 932,
    code: "DXB",
    name: "Dubai Intl Airport",
    cityCode: "DXB",
    cityName: "Dubai",
    countryName: "UNITED ARAB EMIRATES",
    countryCode: "AE",
    address: "Dubai",
    continent: "middleEast",
  },
  {
    id: 884,
    code: "DOH",
    name: "Doha Hamad INTL Airport",
    cityCode: "DOH",
    cityName: "Doha",
    countryName: "QATAR",
    countryCode: "QA",
    address: "Doha",
    continent: "middleEast",
  },
  {
    id: 1633,
    code: "JED",
    name: "King Abdulaziz International Airport",
    cityCode: "JED",
    cityName: "Jeddah",
    countryName: "SAUDI ARABIA",
    countryCode: "SA",
    address: "Jeddah",
    continent: "middleEast",
  },
  {
    id: 3088,
    code: "RUH",
    name: "King Khaled Intl ",
    cityCode: "RUH",
    cityName: "Riyadh",
    countryName: "SAUDI ARABIA",
    countryCode: "SA",
    address: "Riyadh",
    continent: "middleEast",
  },
  {
    id: 2142,
    code: "MCT",
    name: "Muscat International Airport",
    cityCode: "MCT",
    cityName: "Muscat",
    countryName: "OMAN",
    countryCode: "OM",
    address: "Muscat",
    continent: "middleEast",
  },
  {
    id: 244,
    code: "BAH",
    name: "Bahrain Intl Airport",
    cityCode: "BAH",
    cityName: "Muharraq",
    countryName: "BAHRAIN",
    countryCode: "BH",
    address: "Muharraq",
    continent: "middleEast",
  },
  {
    id: 872,
    code: "DMM",
    name: "King Fahad Intl Airport",
    cityCode: "DMM",
    cityName: "Dammam",
    countryName: "SAUDI ARABIA",
    countryCode: "SA",
    address: "Dammam",
    continent: "middleEast",
  },
  {
    id: 2014,
    code: "LHR",
    name: "Heathrow Airport ",
    cityCode: "LON",
    cityName: "London",
    countryName: "UNITED KINGDOM",
    countryCode: "GB",
    address: "London",
    continent: "europe",
  },
  {
    id: 4380,
    code: "ZRH",
    name: "Zurich Intl Airport",
    cityCode: "ZRH",
    cityName: "Zurich",
    countryName: "SWITZERLAND",
    countryCode: "CH",
    address: "Zurich",
    continent: "europe",
  },
  {
    id: 913,
    code: "DUB",
    name: "Dublin Intl Airport",
    cityCode: "DUB",
    cityName: "Dublin",
    countryName: "IRELAND",
    countryCode: "IE",
    address: "Dublin",
    continent: "europe",
  },
  {
    id: 3855,
    code: "WAW",
    name: "Warsaw Intl Airport",
    cityCode: "WAW",
    cityName: "Warsaw",
    countryName: "POLAND",
    countryCode: "PL",
    address: "Warsaw",
    continent: "europe",
  },
  {
    id: 2376,
    code: "MUC",
    name: "Munich Intl Airport",
    cityCode: "MUC",
    cityName: "Munich",
    countryName: "GERMANY",
    countryCode: "DE",
    address: "Munich",
    continent: "europe",
  },
  {
    id: 1579,
    code: "IST",
    name: "Ataturk Intl Airport",
    cityCode: "IST",
    cityName: "Istanbul",
    countryName: "TURKEY",
    countryCode: "TR",
    address: "Istanbul",
    continent: "europe",
  },
  {
    id: 3061,
    code: "FCO",
    name: "Fiumicino Intl Airport",
    cityCode: "ROM",
    cityName: "Rome",
    countryName: "ITALY",
    countryCode: "IT",
    address: "Rome",
    continent: "europe",
  },
  {
    id: 2217,
    code: "MXP",
    name: "Malpensa Intl Airport",
    cityCode: "MIL",
    cityName: "Milan",
    countryName: "ITALY",
    countryCode: "IT",
    address: "Milan",
    continent: "europe",
  },
  {
    id: 2687,
    code: "CDG",
    name: "Charles De Gaulle Intl Airport",
    cityCode: "PAR",
    cityName: "Paris",
    countryName: "FRANCE",
    countryCode: "FR",
    address: "Paris",
    continent: "europe",
  },
  {
    id: 2111,
    code: "MAD",
    name: "Barajas Intl Airport",
    cityCode: "MAD",
    cityName: "Madrid",
    countryName: "SPAIN",
    countryCode: "ES",
    address: "Madrid",
    continent: "europe",
  },
  {
    id: 2773,
    code: "PIX",
    name: "Pico Intl Airport",
    cityCode: "PIX",
    cityName: "Pico Island",
    countryName: "PORTUGAL",
    countryCode: "PT",
    address: "Pico Island",
    continent: "europe",
  },
  {
    id: 131,
    code: "AMS",
    name: "Schiphol Intl Airport",
    cityCode: "AMS",
    cityName: "Amsterdam",
    countryName: "NETHERLANDS",
    countryCode: "NL",
    address: "Amsterdam",
    continent: "europe",
  },
  {
    id: 5,
    code: "JFK",
    name: "John F Kennedy Intl ",
    cityCode: "NYC",
    cityName: "New York",
    countryName: "UNITED STATES",
    countryCode: "US",
    address: "New York",
    continent: "northAmerica",
  },
  {
    id: 1898,
    code: "LAX",
    name: "Los Angeles Intl Airport",
    cityCode: "LAX",
    cityName: "Los Angeles",
    countryName: "UNITED STATES",
    countryCode: "US",
    address: "Los Angeles",
    continent: "northAmerica",
  },
  {
    id: 4263,
    code: "YYZ",
    name: "Lester B Pearson Intl ",
    cityCode: "YTO",
    cityName: "Toronto",
    countryName: "CANADA",
    countryCode: "CA",
    address: "Toronto",
    continent: "northAmerica",
  },
  {
    id: 2209,
    code: "MIA",
    name: "Miami Intl ",
    cityCode: "MIA",
    cityName: "Miami",
    countryName: "UNITED STATES",
    countryCode: "US",
    address: "Miami",
    continent: "northAmerica",
  },
  {
    id: 4167,
    code: "YUL",
    name: "Pierre Elliott Trudeau Intl Airport",
    cityCode: "YMQ",
    cityName: "Montreal",
    countryName: "CANADA",
    countryCode: "CA",
    address: "Montreal",
    continent: "northAmerica",
  },
  {
    id: 202,
    code: "ATL",
    name: "Hartsfield Jackson Intl Airport",
    cityCode: "ATL",
    cityName: "Atlanta",
    countryName: "UNITED STATES",
    countryCode: "US",
    address: "Atlanta",
    continent: "northAmerica",
  },
  {
    id: 3195,
    code: "SFO",
    name: "San Francisco Intl Airport",
    cityCode: "SFO",
    cityName: "San Francisco",
    countryName: "UNITED STATES",
    countryCode: "US",
    address: "San Francisco",
    continent: "northAmerica",
  },
  {
    id: 4283,
    code: "YVR",
    name: "Vancouver Intl Airport",
    cityCode: "YVR",
    cityName: "Vancouver",
    countryName: "CANADA",
    countryCode: "CA",
    address: "Vancouver",
    continent: "northAmerica",
  },
  {
    id: 832,
    code: "DFW",
    name: "Dallas Ft Worth Intl ",
    cityCode: "DFW",
    cityName: "Dallas",
    countryName: "UNITED STATES",
    countryCode: "US",
    address: "Dallas",
    continent: "northAmerica",
  },
  {
    id: 631,
    code: "ORD",
    name: "O'Hare Intl Airport",
    cityCode: "CHI",
    cityName: "Chicago",
    countryName: "UNITED STATES",
    countryCode: "US",
    address: "Chicago",
    continent: "northAmerica",
  },
  {
    id: 423,
    code: "BOS",
    name: "Logan Intl Airport",
    cityCode: "BOS",
    cityName: "Boston",
    countryName: "UNITED STATES",
    countryCode: "US",
    address: "Boston",
    continent: "northAmerica",
  },
  {
    id: 3119,
    code: "GRU",
    name: "Guarulhos Intl Airport",
    cityCode: "SAO",
    cityName: "Sao Paulo",
    countryName: "BRAZIL",
    countryCode: "BR",
    address: "Sao Paulo",
    continent: "southAmerica",
  },
  {
    id: 2175,
    code: "MEX",
    name: "Benito Juarez Intl Airport",
    cityCode: "MEX",
    cityName: "Mexico City",
    countryName: "MEXICO",
    countryCode: "MX",
    address: "Mexico City",
    continent: "southAmerica",
  },
  {
    id: 3245,
    code: "SJO",
    name: "Juan Santa Maria Intl ",
    cityCode: "SJO",
    cityName: "San Jose",
    countryName: "COSTA RICA",
    countryCode: "CR",
    address: "San Jose",
    continent: "southAmerica",
  },
  {
    id: 3122,
    code: "SAP",
    name: "Ramon Villeda Morales Intl Airport",
    cityCode: "SAP",
    cityName: "San Pedro Sula",
    countryName: "HONDURAS",
    countryCode: "HN",
    address: "San Pedro Sula",
    continent: "southAmerica",
  },
  {
    id: 2901,
    code: "PTY",
    name: "Tocumen Intl Airport",
    cityCode: "PTY",
    cityName: "Panama City",
    countryName: "PANAMA",
    countryCode: "PA",
    address: "Panama City",
    continent: "southAmerica",
  },
  {
    id: 3425,
    code: "SYD",
    name: "Sydney Kingsford Smith Intl Airport",
    cityCode: "SYD",
    cityName: "Sydney",
    countryName: "AUSTRALIA",
    countryCode: "AU",
    address: "Sydney",
    continent: "ocenia",
  },
  {
    id: 3881,
    code: "WLG",
    name: "Wellington Intl Airport",
    cityCode: "WLG",
    cityName: "Wellington",
    countryName: "NEW ZEALAND",
    countryCode: "NZ",
    address: "Wellington",
    continent: "ocenia",
  },
  {
    id: 2841,
    code: "POM",
    name: "Jackson Field",
    cityCode: "POM",
    cityName: "Port Moresby",
    countryName: "PAPUA NEW GUINEA",
    countryCode: "PG",
    address: "Port Moresby",
    continent: "ocenia",
  },
  {
    id: 2971,
    code: "RAR",
    name: "Rarotonga Intl Airport",
    cityCode: "RAR",
    cityName: "Rarotonga",
    countryName: "COOK ISLANDS",
    countryCode: "CK",
    address: "Rarotonga",
    continent: "ocenia",
  },
  {
    id: 723,
    code: "CPT",
    name: "Cape Town Intl ",
    cityCode: "CPT",
    cityName: "Cape Town",
    countryName: "SOUTH AFRICA",
    countryCode: "ZA",
    address: "Cape Town",
    continent: "africa",
  },
  {
    id: 31,
    code: "ACC",
    name: "Kotoka Intl Airport",
    cityCode: "ACC",
    cityName: "Accra",
    countryName: "GHANA",
    countryCode: "GH",
    address: "Accra",
    continent: "africa",
  },
  {
    id: 951,
    code: "EBB",
    name: "Entebbe Intl Airport",
    cityCode: "EBB",
    cityName: "Entebbe",
    countryName: "UGANDA",
    countryCode: "UG",
    address: "Entebbe",
    continent: "africa",
  },
  {
    id: 42,
    code: "ADD",
    name: "Bole Intl Airport",
    cityCode: "ADD",
    cityName: "Addis Ababa",
    countryName: "ETHIOPIA",
    countryCode: "ET",
    address: "Addis Ababa",
    continent: "africa",
  },
  {
    id: 111,
    code: "ALG",
    name: "Houari Boumedienne Intl Airport",
    cityCode: "ALG",
    cityName: "Algiers",
    countryName: "ALGERIA",
    countryCode: "DZ",
    address: "Algiers",
    continent: "africa",
  },
  {
    id: 3637,
    code: "TUN",
    name: "Carthage Intl Airport",
    cityCode: "TUN",
    cityName: "Tunis",
    countryName: "TUNISIA",
    countryCode: "TN",
    address: "Tunis",
    continent: "africa",
  },
  {
    id: 807,
    code: "DAR",
    name: "Es Salaam Intl ",
    cityCode: "DAR",
    cityName: "Dar Es Salaam",
    countryName: "TANZANIA",
    countryCode: "TZ",
    address: "Dar Es Salaam",
    continent: "africa",
  },
  {
    id: 4371,
    code: "ZNZ",
    name: "Kisauni Intl Airport",
    cityCode: "ZNZ",
    cityName: "Zanzibar",
    countryName: "TANZANIA",
    countryCode: "TZ",
    address: "Zanzibar",
    continent: "africa",
  },
  {
    id: 543,
    code: "CAI",
    name: "Cairo Intl Airport",
    cityCode: "CAI",
    cityName: "Cairo",
    countryName: "EGYPT",
    countryCode: "EG",
    address: "Cairo",
    continent: "africa",
  },
  {
    id: 2446,
    code: "NBO",
    name: "Jomo Kenyatta Intl ",
    cityCode: "NBO",
    cityName: "Nairobi",
    countryName: "KENYA",
    countryCode: "KE",
    address: "Nairobi",
    continent: "africa",
  },
  {
    id: 1669,
    code: "JNB",
    name: "O R Tambo Intl Airport",
    cityCode: "JNB",
    cityName: "Johannesburg",
    countryName: "SOUTH AFRICA",
    countryCode: "ZA",
    address: "Johannesburg",
    continent: "africa",
  },
];