export const InitialAirportsData = [
  {
    id: "802",
    code: "DAC",
    name: "Hazrat Shahjalal Intl Airport",
    cityCode: "DAC",
    cityName: "Dhaka",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Dhaka",
  },
  {
    id: "932",
    code: "DXB",
    name: "Dubai Intl Airport",
    cityCode: "DXB",
    cityName: "Dubai",
    countryName: "UNITED ARAB EMIRATES",
    countryCode: "AE",
    address: "Dubai",
  },
  {
    id: "4402",
    code: "CXB",
    name: "COXs Bazar Airport",
    cityCode: "CXB",
    cityName: "Coxs Bazar",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Coxs Bazar",
  },
  {
    id: "4404",
    code: "JSR",
    name: "Jashore Airport",
    cityCode: "JSR\r\n",
    cityName: "Jashore",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Jashore",
  },
  {
    id: "4403",
    code: "BZL",
    name: "Barishal Airport",
    cityCode: "BZL\r\n",
    cityName: "Barishal",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Barishal",
  },
  {
    id: "4405",
    code: "RJH",
    name: "Shah Makhdum Airport",
    cityCode: "RJH",
    cityName: "Rajshahi",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Rajshahi",
  },
  {
    id: "4406",
    code: "SPD",
    name: "Saidpur Airport",
    cityCode: "SPD",
    cityName: "Saidpur",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Saidpur",
  },
  {
    id: "2142",
    code: "MCT",
    name: "Seeb Intl ",
    cityCode: "MCT",
    cityName: "Muscat",
    countryName: "OMAN",
    countryCode: "OM",
    address: "Muscat",
  },
  {
    id: "2014",
    code: "LHR",
    name: "Heathrow",
    cityCode: "LON",
    cityName: "London",
    countryName: "UNITED KINGDOM",
    countryCode: "GB",
    address: "London",
  },
  {
    id: "5",
    code: "JFK",
    name: "John F Kennedy Intl ",
    cityCode: "NYC",
    cityName: "New York",
    countryName: "UNITED STATES",
    countryCode: "US",
    address: "New York",
  },
];
