export const mobileFromData = [
  {
    id: 802,
    code: "DAC",
    name: "Hazrat Shahjalal Intl Airport",
    cityCode: "DAC",
    cityName: "Dhaka",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Dhaka",
  },
  {
    id: 1844,
    code: "KUL",
    name: "Kuala Lumpur Intl Airport",
    cityCode: "KUL",
    cityName: "Kuala Lumpur",
    countryName: "MALAYSIA",
    countryCode: "MY",
    address: "Kuala Lumpur",
  },
  {
    id: 932,
    code: "DXB",
    name: "Dubai Intl Airport",
    cityCode: "DXB",
    cityName: "Dubai",
    countryName: "UNITED ARAB EMIRATES",
    countryCode: "AE",
    address: "Dubai",
  },
  {
    id: 4402,
    code: "CXB",
    name: "COX's Bazar Airport",
    cityCode: "CXB",
    cityName: "Cox's Bazar",
    countryName: "BANGLADESH",
    countryCode: "BD",
    address: "Cox's Bazar",
  },
  {
    id: 5,
    code: "JFK",
    name: "John F Kennedy Intl",
    cityCode: "NYC",
    cityName: "New York",
    countryName: "UNITED STATES",
    countryCode: "US",
    address: "New York",
  },
  {
    id: 3232,
    code: "SIN",
    name: "Changi Intl Airport",
    cityCode: "SIN",
    cityName: "Singapore",
    countryName: "SINGAPORE",
    countryCode: "SG",
    address: "Singapore",
  },
];
