const CountryListWithCode = [
  {
    id: 19,
    name: "Bangladesh",
    countryCode: "BD",
    phoneCode: "880",
    flag: "https://flagcdn.com/w320/bd.png",
  },
  {
    id: 1,
    name: "Afghanistan",
    countryCode: "AF",
    phoneCode: "93",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
  },
  {
    id: 2,
    name: "Åland Islands",
    countryCode: "AX",
    phoneCode: "358",
    flag: "https://flagcdn.com/w320/ax.png",
  },
  {
    id: 3,
    name: "Albania",
    countryCode: "AL",
    phoneCode: "355",
    flag: "https://flagcdn.com/w320/al.png",
  },
  {
    id: 4,
    name: "Algeria",
    countryCode: "DZ",
    phoneCode: "213",
    flag: "https://flagcdn.com/w320/dz.png",
  },
  {
    id: 5,
    name: "American Samoa",
    countryCode: "AS",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/as.png",
  },
  {
    id: 6,
    name: "Andorra",
    countryCode: "AD",
    phoneCode: "376",
    flag: "https://flagcdn.com/w320/ad.png",
  },
  {
    id: 7,
    name: "Angola",
    countryCode: "AO",
    phoneCode: "244",
    flag: "https://flagcdn.com/w320/ao.png",
  },
  {
    id: 8,
    name: "Anguilla",
    countryCode: "AI",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/ai.png",
  },
  {
    id: 9,
    name: "Antarctica",
    countryCode: "AQ",
    phoneCode: "672",
    flag: "https://flagcdn.com/w320/aq.png",
  },
  {
    id: 10,
    name: "Antigua and Barbuda",
    countryCode: "AG",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/ag.png",
  },
  {
    id: 11,
    name: "Argentina",
    countryCode: "AR",
    phoneCode: "54",
    flag: "https://flagcdn.com/w320/ar.png",
  },
  {
    id: 12,
    name: "Armenia",
    countryCode: "AM",
    phoneCode: "374",
    flag: "https://flagcdn.com/w320/am.png",
  },
  {
    id: 13,
    name: "Aruba",
    countryCode: "AW",
    phoneCode: "297",
    flag: "https://flagcdn.com/w320/aw.png",
  },
  {
    id: 14,
    name: "Australia",
    countryCode: "AU",
    phoneCode: "61",
    flag: "https://flagcdn.com/w320/au.png",
  },
  {
    id: 15,
    name: "Austria",
    countryCode: "AT",
    phoneCode: "43",
    flag: "https://flagcdn.com/w320/at.png",
  },
  {
    id: 16,
    name: "Azerbaijan",
    countryCode: "AZ",
    phoneCode: "994",
    flag: "https://flagcdn.com/w320/az.png",
  },
  {
    id: 17,
    name: "Bahamas",
    countryCode: "BS",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/bs.png",
  },
  {
    id: 18,
    name: "Bahrain",
    countryCode: "BH",
    phoneCode: "973",
    flag: "https://flagcdn.com/w320/bh.png",
  },
  // {
  //   id: 19,
  //   name: "Bangladesh",
  //   countryCode: "BD",
  //   phoneCode: "880",
  //   flag: "https://flagcdn.com/w320/bd.png",
  // },
  {
    id: 20,
    name: "Barbados",
    countryCode: "BB",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/bb.png",
  },
  {
    id: 21,
    name: "Belarus",
    countryCode: "BY",
    phoneCode: "375",
    flag: "https://flagcdn.com/w320/by.png",
  },
  {
    id: 22,
    name: "Belgium",
    countryCode: "BE",
    phoneCode: "32",
    flag: "https://flagcdn.com/w320/be.png",
  },
  {
    id: 23,
    name: "Belize",
    countryCode: "BZ",
    phoneCode: "501",
    flag: "https://flagcdn.com/w320/bz.png",
  },
  {
    id: 24,
    name: "Benin",
    countryCode: "BJ",
    phoneCode: "229",
    flag: "https://flagcdn.com/w320/bj.png",
  },
  {
    id: 25,
    name: "Bermuda",
    countryCode: "BM",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/bm.png",
  },
  {
    id: 26,
    name: "Bhutan",
    countryCode: "BT",
    phoneCode: "975",
    flag: "https://flagcdn.com/w320/bt.png",
  },
  {
    id: 27,
    name: "Bolivia (Plurinational State of)",
    countryCode: "BO",
    phoneCode: "591",
    flag: "https://flagcdn.com/w320/bo.png",
  },
  {
    id: 28,
    name: "Bonaire, Sint Eustatius and Saba",
    countryCode: "BQ",
    phoneCode: "599",
    flag: "https://flagcdn.com/w320/bq.png",
  },
  {
    id: 29,
    name: "Bosnia and Herzegovina",
    countryCode: "BA",
    phoneCode: "387",
    flag: "https://flagcdn.com/w320/ba.png",
  },
  {
    id: 30,
    name: "Botswana",
    countryCode: "BW",
    phoneCode: "267",
    flag: "https://flagcdn.com/w320/bw.png",
  },
  {
    id: 31,
    name: "Bouvet Island",
    countryCode: "BV",
    phoneCode: "47",
    flag: "https://flagcdn.com/w320/bv.png",
  },
  {
    id: 32,
    name: "Brazil",
    countryCode: "BR",
    phoneCode: "55",
    flag: "https://flagcdn.com/w320/br.png",
  },
  {
    id: 33,
    name: "British Indian Ocean Territory",
    countryCode: "IO",
    phoneCode: "246",
    flag: "https://flagcdn.com/w320/io.png",
  },
  {
    id: 34,
    name: "United States Minor Outlying Islands",
    countryCode: "UM",
    phoneCode: "246",
    flag: "https://flagcdn.com/w320/um.png",
  },
  {
    id: 35,
    name: "Virgin Islands (British)",
    countryCode: "VG",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/vg.png",
  },
  {
    id: 36,
    name: "Virgin Islands (U.S.)",
    countryCode: "VI",
    phoneCode: "1 340",
    flag: "https://flagcdn.com/w320/vi.png",
  },
  {
    id: 37,
    name: "Brunei Darussalam",
    countryCode: "BN",
    phoneCode: "673",
    flag: "https://flagcdn.com/w320/bn.png",
  },
  {
    id: 38,
    name: "Bulgaria",
    countryCode: "BG",
    phoneCode: "359",
    flag: "https://flagcdn.com/w320/bg.png",
  },
  {
    id: 39,
    name: "Burkina Faso",
    countryCode: "BF",
    phoneCode: "226",
    flag: "https://flagcdn.com/w320/bf.png",
  },
  {
    id: 40,
    name: "Burundi",
    countryCode: "BI",
    phoneCode: "257",
    flag: "https://flagcdn.com/w320/bi.png",
  },
  {
    id: 41,
    name: "Cambodia",
    countryCode: "KH",
    phoneCode: "855",
    flag: "https://flagcdn.com/w320/kh.png",
  },
  {
    id: 42,
    name: "Cameroon",
    countryCode: "CM",
    phoneCode: "237",
    flag: "https://flagcdn.com/w320/cm.png",
  },
  {
    id: 43,
    name: "Canada",
    countryCode: "CA",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/ca.png",
  },
  {
    id: 44,
    name: "Cabo Verde",
    countryCode: "CV",
    phoneCode: "238",
    flag: "https://flagcdn.com/w320/cv.png",
  },
  {
    id: 45,
    name: "Cayman Islands",
    countryCode: "KY",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/ky.png",
  },
  {
    id: 46,
    name: "Central African Republic",
    countryCode: "CF",
    phoneCode: "236",
    flag: "https://flagcdn.com/w320/cf.png",
  },
  {
    id: 47,
    name: "Chad",
    countryCode: "TD",
    phoneCode: "235",
    flag: "https://flagcdn.com/w320/td.png",
  },
  {
    id: 48,
    name: "Chile",
    countryCode: "CL",
    phoneCode: "56",
    flag: "https://flagcdn.com/w320/cl.png",
  },
  {
    id: 49,
    name: "China",
    countryCode: "CN",
    phoneCode: "86",
    flag: "https://flagcdn.com/w320/cn.png",
  },
  {
    id: 50,
    name: "Christmas Island",
    countryCode: "CX",
    phoneCode: "61",
    flag: "https://flagcdn.com/w320/cx.png",
  },
  {
    id: 51,
    name: "Cocos (Keeling) Islands",
    countryCode: "CC",
    phoneCode: "61",
    flag: "https://flagcdn.com/w320/cc.png",
  },
  {
    id: 52,
    name: "Colombia",
    countryCode: "CO",
    phoneCode: "57",
    flag: "https://flagcdn.com/w320/co.png",
  },
  {
    id: 53,
    name: "Comoros",
    countryCode: "KM",
    phoneCode: "269",
    flag: "https://flagcdn.com/w320/km.png",
  },
  {
    id: 54,
    name: "Congo",
    countryCode: "CG",
    phoneCode: "242",
    flag: "https://flagcdn.com/w320/cg.png",
  },
  {
    id: 55,
    name: "Congo (Democratic Republic of the)",
    countryCode: "CD",
    phoneCode: "243",
    flag: "https://flagcdn.com/w320/cd.png",
  },
  {
    id: 56,
    name: "Cook Islands",
    countryCode: "CK",
    phoneCode: "682",
    flag: "https://flagcdn.com/w320/ck.png",
  },
  {
    id: 57,
    name: "Costa Rica",
    countryCode: "CR",
    phoneCode: "506",
    flag: "https://flagcdn.com/w320/cr.png",
  },
  {
    id: 58,
    name: "Croatia",
    countryCode: "HR",
    phoneCode: "385",
    flag: "https://flagcdn.com/w320/hr.png",
  },
  {
    id: 59,
    name: "Cuba",
    countryCode: "CU",
    phoneCode: "53",
    flag: "https://flagcdn.com/w320/cu.png",
  },
  {
    id: 60,
    name: "Curaçao",
    countryCode: "CW",
    phoneCode: "599",
    flag: "https://flagcdn.com/w320/cw.png",
  },
  {
    id: 61,
    name: "Cyprus",
    countryCode: "CY",
    phoneCode: "357",
    flag: "https://flagcdn.com/w320/cy.png",
  },
  {
    id: 62,
    name: "Czech Republic",
    countryCode: "CZ",
    phoneCode: "420",
    flag: "https://flagcdn.com/w320/cz.png",
  },
  {
    id: 63,
    name: "Denmark",
    countryCode: "DK",
    phoneCode: "45",
    flag: "https://flagcdn.com/w320/dk.png",
  },
  {
    id: 64,
    name: "Djibouti",
    countryCode: "DJ",
    phoneCode: "253",
    flag: "https://flagcdn.com/w320/dj.png",
  },
  {
    id: 65,
    name: "Dominica",
    countryCode: "DM",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/dm.png",
  },
  {
    id: 66,
    name: "Dominican Republic",
    countryCode: "DO",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/do.png",
  },
  {
    id: 67,
    name: "Ecuador",
    countryCode: "EC",
    phoneCode: "593",
    flag: "https://flagcdn.com/w320/ec.png",
  },
  {
    id: 68,
    name: "Egypt",
    countryCode: "EG",
    phoneCode: "20",
    flag: "https://flagcdn.com/w320/eg.png",
  },
  {
    id: 69,
    name: "El Salvador",
    countryCode: "SV",
    phoneCode: "503",
    flag: "https://flagcdn.com/w320/sv.png",
  },
  {
    id: 70,
    name: "Equatorial Guinea",
    countryCode: "GQ",
    phoneCode: "240",
    flag: "https://flagcdn.com/w320/gq.png",
  },
  {
    id: 71,
    name: "Eritrea",
    countryCode: "ER",
    phoneCode: "291",
    flag: "https://flagcdn.com/w320/er.png",
  },
  {
    id: 72,
    name: "Estonia",
    countryCode: "EE",
    phoneCode: "372",
    flag: "https://flagcdn.com/w320/ee.png",
  },
  {
    id: 73,
    name: "Ethiopia",
    countryCode: "ET",
    phoneCode: "251",
    flag: "https://flagcdn.com/w320/et.png",
  },
  {
    id: 74,
    name: "Falkland Islands (Malvinas)",
    countryCode: "FK",
    phoneCode: "500",
    flag: "https://flagcdn.com/w320/fk.png",
  },
  {
    id: 75,
    name: "Faroe Islands",
    countryCode: "FO",
    phoneCode: "298",
    flag: "https://flagcdn.com/w320/fo.png",
  },
  {
    id: 76,
    name: "Fiji",
    countryCode: "FJ",
    phoneCode: "679",
    flag: "https://flagcdn.com/w320/fj.png",
  },
  {
    id: 77,
    name: "Finland",
    countryCode: "FI",
    phoneCode: "358",
    flag: "https://flagcdn.com/w320/fi.png",
  },
  {
    id: 78,
    name: "France",
    countryCode: "FR",
    phoneCode: "33",
    flag: "https://flagcdn.com/w320/fr.png",
  },
  {
    id: 79,
    name: "French Guiana",
    countryCode: "GF",
    phoneCode: "594",
    flag: "https://flagcdn.com/w320/gf.png",
  },
  {
    id: 80,
    name: "French Polynesia",
    countryCode: "PF",
    phoneCode: "689",
    flag: "https://flagcdn.com/w320/pf.png",
  },
  {
    id: 81,
    name: "French Southern Territories",
    countryCode: "TF",
    phoneCode: "262",
    flag: "https://flagcdn.com/w320/tf.png",
  },
  {
    id: 82,
    name: "Gabon",
    countryCode: "GA",
    phoneCode: "241",
    flag: "https://flagcdn.com/w320/ga.png",
  },
  {
    id: 83,
    name: "Gambia",
    countryCode: "GM",
    phoneCode: "220",
    flag: "https://flagcdn.com/w320/gm.png",
  },
  {
    id: 84,
    name: "Georgia",
    countryCode: "GE",
    phoneCode: "995",
    flag: "https://flagcdn.com/w320/ge.png",
  },
  {
    id: 85,
    name: "Germany",
    countryCode: "DE",
    phoneCode: "49",
    flag: "https://flagcdn.com/w320/de.png",
  },
  {
    id: 86,
    name: "Ghana",
    countryCode: "GH",
    phoneCode: "233",
    flag: "https://flagcdn.com/w320/gh.png",
  },
  {
    id: 87,
    name: "Gibraltar",
    countryCode: "GI",
    phoneCode: "350",
    flag: "https://flagcdn.com/w320/gi.png",
  },
  {
    id: 88,
    name: "Greece",
    countryCode: "GR",
    phoneCode: "30",
    flag: "https://flagcdn.com/w320/gr.png",
  },
  {
    id: 89,
    name: "Greenland",
    countryCode: "GL",
    phoneCode: "299",
    flag: "https://flagcdn.com/w320/gl.png",
  },
  {
    id: 90,
    name: "Grenada",
    countryCode: "GD",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/gd.png",
  },
  {
    id: 91,
    name: "Guadeloupe",
    countryCode: "GP",
    phoneCode: "590",
    flag: "https://flagcdn.com/w320/gp.png",
  },
  {
    id: 92,
    name: "Guam",
    countryCode: "GU",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/gu.png",
  },
  {
    id: 93,
    name: "Guatemala",
    countryCode: "GT",
    phoneCode: "502",
    flag: "https://flagcdn.com/w320/gt.png",
  },
  {
    id: 94,
    name: "Guernsey",
    countryCode: "GG",
    phoneCode: "44",
    flag: "https://flagcdn.com/w320/gg.png",
  },
  {
    id: 95,
    name: "Guinea",
    countryCode: "GN",
    phoneCode: "224",
    flag: "https://flagcdn.com/w320/gn.png",
  },
  {
    id: 96,
    name: "Guinea-Bissau",
    countryCode: "GW",
    phoneCode: "245",
    flag: "https://flagcdn.com/w320/gw.png",
  },
  {
    id: 97,
    name: "Guyana",
    countryCode: "GY",
    phoneCode: "592",
    flag: "https://flagcdn.com/w320/gy.png",
  },
  {
    id: 98,
    name: "Haiti",
    countryCode: "HT",
    phoneCode: "509",
    flag: "https://flagcdn.com/w320/ht.png",
  },
  {
    id: 99,
    name: "Heard Island and McDonald Islands",
    countryCode: "HM",
    phoneCode: "672",
    flag: "https://flagcdn.com/w320/hm.png",
  },
  {
    id: 100,
    name: "Vatican City",
    countryCode: "VA",
    phoneCode: "379",
    flag: "https://flagcdn.com/w320/va.png",
  },
  {
    id: 101,
    name: "Honduras",
    countryCode: "HN",
    phoneCode: "504",
    flag: "https://flagcdn.com/w320/hn.png",
  },
  {
    id: 102,
    name: "Hungary",
    countryCode: "HU",
    phoneCode: "36",
    flag: "https://flagcdn.com/w320/hu.png",
  },
  {
    id: 103,
    name: "Hong Kong",
    countryCode: "HK",
    phoneCode: "852",
    flag: "https://flagcdn.com/w320/hk.png",
  },
  {
    id: 104,
    name: "Iceland",
    countryCode: "IS",
    phoneCode: "354",
    flag: "https://flagcdn.com/w320/is.png",
  },
  {
    id: 105,
    name: "India",
    countryCode: "IN",
    phoneCode: "91",
    flag: "https://flagcdn.com/w320/in.png",
  },
  {
    id: 106,
    name: "Indonesia",
    countryCode: "ID",
    phoneCode: "62",
    flag: "https://flagcdn.com/w320/id.png",
  },
  {
    id: 107,
    name: "Ivory Coast",
    countryCode: "CI",
    phoneCode: "225",
    flag: "https://flagcdn.com/w320/ci.png",
  },
  {
    id: 108,
    name: "Iran (Islamic Republic of)",
    countryCode: "IR",
    phoneCode: "98",
    flag: "https://flagcdn.com/w320/ir.png",
  },
  {
    id: 109,
    name: "Iraq",
    countryCode: "IQ",
    phoneCode: "964",
    flag: "https://flagcdn.com/w320/iq.png",
  },
  {
    id: 110,
    name: "Ireland",
    countryCode: "IE",
    phoneCode: "353",
    flag: "https://flagcdn.com/w320/ie.png",
  },
  {
    id: 111,
    name: "Isle of Man",
    countryCode: "IM",
    phoneCode: "44",
    flag: "https://flagcdn.com/w320/im.png",
  },
  {
    id: 112,
    name: "Israel",
    countryCode: "IL",
    phoneCode: "972",
    flag: "https://flagcdn.com/w320/il.png",
  },
  {
    id: 113,
    name: "Italy",
    countryCode: "IT",
    phoneCode: "39",
    flag: "https://flagcdn.com/w320/it.png",
  },
  {
    id: 114,
    name: "Jamaica",
    countryCode: "JM",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/jm.png",
  },
  {
    id: 115,
    name: "Japan",
    countryCode: "JP",
    phoneCode: "81",
    flag: "https://flagcdn.com/w320/jp.png",
  },
  {
    id: 116,
    name: "Jersey",
    countryCode: "JE",
    phoneCode: "44",
    flag: "https://flagcdn.com/w320/je.png",
  },
  {
    id: 117,
    name: "Jordan",
    countryCode: "JO",
    phoneCode: "962",
    flag: "https://flagcdn.com/w320/jo.png",
  },
  {
    id: 118,
    name: "Kazakhstan",
    countryCode: "KZ",
    phoneCode: "76",
    flag: "https://flagcdn.com/w320/kz.png",
  },
  {
    id: 119,
    name: "Kenya",
    countryCode: "KE",
    phoneCode: "254",
    flag: "https://flagcdn.com/w320/ke.png",
  },
  {
    id: 120,
    name: "Kiribati",
    countryCode: "KI",
    phoneCode: "686",
    flag: "https://flagcdn.com/w320/ki.png",
  },
  {
    id: 121,
    name: "Kuwait",
    countryCode: "KW",
    phoneCode: "965",
    flag: "https://flagcdn.com/w320/kw.png",
  },
  {
    id: 122,
    name: "Kyrgyzstan",
    countryCode: "KG",
    phoneCode: "996",
    flag: "https://flagcdn.com/w320/kg.png",
  },
  {
    id: 123,
    name: "Lao People's Democratic Republic",
    countryCode: "LA",
    phoneCode: "856",
    flag: "https://flagcdn.com/w320/la.png",
  },
  {
    id: 124,
    name: "Latvia",
    countryCode: "LV",
    phoneCode: "371",
    flag: "https://flagcdn.com/w320/lv.png",
  },
  {
    id: 125,
    name: "Lebanon",
    countryCode: "LB",
    phoneCode: "961",
    flag: "https://flagcdn.com/w320/lb.png",
  },
  {
    id: 126,
    name: "Lesotho",
    countryCode: "LS",
    phoneCode: "266",
    flag: "https://flagcdn.com/w320/ls.png",
  },
  {
    id: 127,
    name: "Liberia",
    countryCode: "LR",
    phoneCode: "231",
    flag: "https://flagcdn.com/w320/lr.png",
  },
  {
    id: 128,
    name: "Libya",
    countryCode: "LY",
    phoneCode: "218",
    flag: "https://flagcdn.com/w320/ly.png",
  },
  {
    id: 129,
    name: "Liechtenstein",
    countryCode: "LI",
    phoneCode: "423",
    flag: "https://flagcdn.com/w320/li.png",
  },
  {
    id: 130,
    name: "Lithuania",
    countryCode: "LT",
    phoneCode: "370",
    flag: "https://flagcdn.com/w320/lt.png",
  },
  {
    id: 131,
    name: "Luxembourg",
    countryCode: "LU",
    phoneCode: "352",
    flag: "https://flagcdn.com/w320/lu.png",
  },
  {
    id: 132,
    name: "Macao",
    countryCode: "MO",
    phoneCode: "853",
    flag: "https://flagcdn.com/w320/mo.png",
  },
  {
    id: 133,
    name: "North Macedonia",
    countryCode: "MK",
    phoneCode: "389",
    flag: "https://flagcdn.com/w320/mk.png",
  },
  {
    id: 134,
    name: "Madagascar",
    countryCode: "MG",
    phoneCode: "261",
    flag: "https://flagcdn.com/w320/mg.png",
  },
  {
    id: 135,
    name: "Malawi",
    countryCode: "MW",
    phoneCode: "265",
    flag: "https://flagcdn.com/w320/mw.png",
  },
  {
    id: 136,
    name: "Malaysia",
    countryCode: "MY",
    phoneCode: "60",
    flag: "https://flagcdn.com/w320/my.png",
  },
  {
    id: 137,
    name: "Maldives",
    countryCode: "MV",
    phoneCode: "960",
    flag: "https://flagcdn.com/w320/mv.png",
  },
  {
    id: 138,
    name: "Mali",
    countryCode: "ML",
    phoneCode: "223",
    flag: "https://flagcdn.com/w320/ml.png",
  },
  {
    id: 139,
    name: "Malta",
    countryCode: "MT",
    phoneCode: "356",
    flag: "https://flagcdn.com/w320/mt.png",
  },
  {
    id: 140,
    name: "Marshall Islands",
    countryCode: "MH",
    phoneCode: "692",
    flag: "https://flagcdn.com/w320/mh.png",
  },
  {
    id: 141,
    name: "Martinique",
    countryCode: "MQ",
    phoneCode: "596",
    flag: "https://flagcdn.com/w320/mq.png",
  },
  {
    id: 142,
    name: "Mauritania",
    countryCode: "MR",
    phoneCode: "222",
    flag: "https://flagcdn.com/w320/mr.png",
  },
  {
    id: 143,
    name: "Mauritius",
    countryCode: "MU",
    phoneCode: "230",
    flag: "https://flagcdn.com/w320/mu.png",
  },
  {
    id: 144,
    name: "Mayotte",
    countryCode: "YT",
    phoneCode: "262",
    flag: "https://flagcdn.com/w320/yt.png",
  },
  {
    id: 145,
    name: "Mexico",
    countryCode: "MX",
    phoneCode: "52",
    flag: "https://flagcdn.com/w320/mx.png",
  },
  {
    id: 146,
    name: "Micronesia (Federated States of)",
    countryCode: "FM",
    phoneCode: "691",
    flag: "https://flagcdn.com/w320/fm.png",
  },
  {
    id: 147,
    name: "Moldova (Republic of)",
    countryCode: "MD",
    phoneCode: "373",
    flag: "https://flagcdn.com/w320/md.png",
  },
  {
    id: 148,
    name: "Monaco",
    countryCode: "MC",
    phoneCode: "377",
    flag: "https://flagcdn.com/w320/mc.png",
  },
  {
    id: 149,
    name: "Mongolia",
    countryCode: "MN",
    phoneCode: "976",
    flag: "https://flagcdn.com/w320/mn.png",
  },
  {
    id: 150,
    name: "Montenegro",
    countryCode: "ME",
    phoneCode: "382",
    flag: "https://flagcdn.com/w320/me.png",
  },
  {
    id: 151,
    name: "Montserrat",
    countryCode: "MS",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/ms.png",
  },
  {
    id: 152,
    name: "Morocco",
    countryCode: "MA",
    phoneCode: "212",
    flag: "https://flagcdn.com/w320/ma.png",
  },
  {
    id: 153,
    name: "Mozambique",
    countryCode: "MZ",
    phoneCode: "258",
    flag: "https://flagcdn.com/w320/mz.png",
  },
  {
    id: 154,
    name: "Myanmar",
    countryCode: "MM",
    phoneCode: "95",
    flag: "https://flagcdn.com/w320/mm.png",
  },
  {
    id: 155,
    name: "Namibia",
    countryCode: "NA",
    phoneCode: "264",
    flag: "https://flagcdn.com/w320/na.png",
  },
  {
    id: 156,
    name: "Nauru",
    countryCode: "NR",
    phoneCode: "674",
    flag: "https://flagcdn.com/w320/nr.png",
  },
  {
    id: 157,
    name: "Nepal",
    countryCode: "NP",
    phoneCode: "977",
    flag: "https://flagcdn.com/w320/np.png",
  },
  {
    id: 158,
    name: "Netherlands",
    countryCode: "NL",
    phoneCode: "31",
    flag: "https://flagcdn.com/w320/nl.png",
  },
  {
    id: 159,
    name: "New Caledonia",
    countryCode: "NC",
    phoneCode: "687",
    flag: "https://flagcdn.com/w320/nc.png",
  },
  {
    id: 160,
    name: "New Zealand",
    countryCode: "NZ",
    phoneCode: "64",
    flag: "https://flagcdn.com/w320/nz.png",
  },
  {
    id: 161,
    name: "Nicaragua",
    countryCode: "NI",
    phoneCode: "505",
    flag: "https://flagcdn.com/w320/ni.png",
  },
  {
    id: 162,
    name: "Niger",
    countryCode: "NE",
    phoneCode: "227",
    flag: "https://flagcdn.com/w320/ne.png",
  },
  {
    id: 163,
    name: "Nigeria",
    countryCode: "NG",
    phoneCode: "234",
    flag: "https://flagcdn.com/w320/ng.png",
  },
  {
    id: 164,
    name: "Niue",
    countryCode: "NU",
    phoneCode: "683",
    flag: "https://flagcdn.com/w320/nu.png",
  },
  {
    id: 165,
    name: "Norfolk Island",
    countryCode: "NF",
    phoneCode: "672",
    flag: "https://flagcdn.com/w320/nf.png",
  },
  {
    id: 166,
    name: "Korea (Democratic People's Republic of)",
    countryCode: "KP",
    phoneCode: "850",
    flag: "https://flagcdn.com/w320/kp.png",
  },
  {
    id: 167,
    name: "Northern Mariana Islands",
    countryCode: "MP",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/mp.png",
  },
  {
    id: 168,
    name: "Norway",
    countryCode: "NO",
    phoneCode: "47",
    flag: "https://flagcdn.com/w320/no.png",
  },
  {
    id: 169,
    name: "Oman",
    countryCode: "OM",
    phoneCode: "968",
    flag: "https://flagcdn.com/w320/om.png",
  },
  {
    id: 170,
    name: "Pakistan",
    countryCode: "PK",
    phoneCode: "92",
    flag: "https://flagcdn.com/w320/pk.png",
  },
  {
    id: 171,
    name: "Palau",
    countryCode: "PW",
    phoneCode: "680",
    flag: "https://flagcdn.com/w320/pw.png",
  },
  {
    id: 172,
    name: "Palestine, State of",
    countryCode: "PS",
    phoneCode: "970",
    flag: "https://flagcdn.com/w320/ps.png",
  },
  {
    id: 173,
    name: "Panama",
    countryCode: "PA",
    phoneCode: "507",
    flag: "https://flagcdn.com/w320/pa.png",
  },
  {
    id: 174,
    name: "Papua New Guinea",
    countryCode: "PG",
    phoneCode: "675",
    flag: "https://flagcdn.com/w320/pg.png",
  },
  {
    id: 175,
    name: "Paraguay",
    countryCode: "PY",
    phoneCode: "595",
    flag: "https://flagcdn.com/w320/py.png",
  },
  {
    id: 176,
    name: "Peru",
    countryCode: "PE",
    phoneCode: "51",
    flag: "https://flagcdn.com/w320/pe.png",
  },
  {
    id: 177,
    name: "Philippines",
    countryCode: "PH",
    phoneCode: "63",
    flag: "https://flagcdn.com/w320/ph.png",
  },
  {
    id: 178,
    name: "Pitcairn",
    countryCode: "PN",
    phoneCode: "64",
    flag: "https://flagcdn.com/w320/pn.png",
  },
  {
    id: 179,
    name: "Poland",
    countryCode: "PL",
    phoneCode: "48",
    flag: "https://flagcdn.com/w320/pl.png",
  },
  {
    id: 180,
    name: "Portugal",
    countryCode: "PT",
    phoneCode: "351",
    flag: "https://flagcdn.com/w320/pt.png",
  },
  {
    id: 181,
    name: "Puerto Rico",
    countryCode: "PR",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/pr.png",
  },
  {
    id: 182,
    name: "Qatar",
    countryCode: "QA",
    phoneCode: "974",
    flag: "https://flagcdn.com/w320/qa.png",
  },
  {
    id: 183,
    name: "Republic of Kosovo",
    countryCode: "XK",
    phoneCode: "383",
    flag: "https://flagcdn.com/w320/xk.png",
  },
  {
    id: 184,
    name: "Réunion",
    countryCode: "RE",
    phoneCode: "262",
    flag: "https://flagcdn.com/w320/re.png",
  },
  {
    id: 185,
    name: "Romania",
    countryCode: "RO",
    phoneCode: "40",
    flag: "https://flagcdn.com/w320/ro.png",
  },
  {
    id: 186,
    name: "Russian Federation",
    countryCode: "RU",
    phoneCode: "7",
    flag: "https://flagcdn.com/w320/ru.png",
  },
  {
    id: 187,
    name: "Rwanda",
    countryCode: "RW",
    phoneCode: "250",
    flag: "https://flagcdn.com/w320/rw.png",
  },
  {
    id: 188,
    name: "Saint Barthélemy",
    countryCode: "BL",
    phoneCode: "590",
    flag: "https://flagcdn.com/w320/bl.png",
  },
  {
    id: 189,
    name: "Saint Helena, Ascension and Tristan da Cunha",
    countryCode: "SH",
    phoneCode: "290",
    flag: "https://flagcdn.com/w320/sh.png",
  },
  {
    id: 190,
    name: "Saint Kitts and Nevis",
    countryCode: "KN",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/kn.png",
  },
  {
    id: 191,
    name: "Saint Lucia",
    countryCode: "LC",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/lc.png",
  },
  {
    id: 192,
    name: "Saint Martin (French part)",
    countryCode: "MF",
    phoneCode: "590",
    flag: "https://flagcdn.com/w320/mf.png",
  },
  {
    id: 193,
    name: "Saint Pierre and Miquelon",
    countryCode: "PM",
    phoneCode: "508",
    flag: "https://flagcdn.com/w320/pm.png",
  },
  {
    id: 194,
    name: "Saint Vincent and the Grenadines",
    countryCode: "VC",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/vc.png",
  },
  {
    id: 195,
    name: "Samoa",
    countryCode: "WS",
    phoneCode: "685",
    flag: "https://flagcdn.com/w320/ws.png",
  },
  {
    id: 196,
    name: "San Marino",
    countryCode: "SM",
    phoneCode: "378",
    flag: "https://flagcdn.com/w320/sm.png",
  },
  {
    id: 197,
    name: "Sao Tome and Principe",
    countryCode: "ST",
    phoneCode: "239",
    flag: "https://flagcdn.com/w320/st.png",
  },
  {
    id: 198,
    name: "Saudi Arabia",
    countryCode: "SA",
    phoneCode: "966",
    flag: "https://flagcdn.com/w320/sa.png",
  },
  {
    id: 199,
    name: "Senegal",
    countryCode: "SN",
    phoneCode: "221",
    flag: "https://flagcdn.com/w320/sn.png",
  },
  {
    id: 200,
    name: "Serbia",
    countryCode: "RS",
    phoneCode: "381",
    flag: "https://flagcdn.com/w320/rs.png",
  },
];

export default CountryListWithCode;
